//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BarMarket.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Beverage
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Type { get; set; }
        public string Creator { get; set; }
        public Nullable<decimal> Volume { get; set; }
        public Nullable<decimal> Percent { get; set; }
        public string Supplier { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<long> Quantity { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }
    }
}
