//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BarMarket.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductSupply
    {
        public int ID { get; set; }
        public string Beverage_Name { get; set; }
        public Nullable<int> Beverage_ID { get; set; }
        public string Beverage_Type { get; set; }
        public Nullable<decimal> Beverage_Percent { get; set; }
        public Nullable<decimal> BeverageItem_Weight { get; set; }
        public string Beverage_Creator { get; set; }
        public Nullable<int> Supply_ID { get; set; }
        public Nullable<System.DateTime> Supply_Date { get; set; }
        public string Supplier { get; set; }
        public Nullable<long> Quantity { get; set; }
        public Nullable<bool> Activated { get; set; }
        public string Action { get; set; }
        public string Username { get; set; }
        public Nullable<decimal> Beverage_Volume { get; set; }
        public Nullable<decimal> Beverage_Price { get; set; }
        public int ProductId { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
